#!/usr/bin/env python3
"""Checks out Dawn and the third-party projects its CMake build needs, at the
commits Skia pins in its DEPS file.

Skia's tools/git-sync-deps syncs every dependency in DEPS (angle, freetype,
icu, ...). A standalone Dawn build only needs Dawn itself plus the directories
third_party/dawn/cmake_utils.py hands to Dawn's CMake, so this writes a DEPS
file reduced to those entries next to the real one and runs git-sync-deps on
it. The commits are the ones the Skia binaries were built against, which is
the point: the prebuilt Dawn is the Dawn that Skia Graphite linked.

Usage: sync-dawn-deps.py <path to externals/skia>
"""

import os
import re
import subprocess
import sys

DAWN = "third_party/externals/dawn"


def parse_deps(path):
  scope = {}
  with open(path) as f:
    # Same evaluation as tools/git-sync-deps: DEPS is a Python literal that
    # resolves Var() against its own vars dictionary.
    exec("def Var(x): return vars[x]\n" + f.read(), scope)
  return scope["deps"]


def dawn_dependencies(skia):
  """The DEPS entries Dawn's CMake build reads, from the list Skia passes it."""
  cmake_utils = os.path.join(skia, "third_party", "dawn", "cmake_utils.py")
  with open(cmake_utils) as f:
    names = re.findall(r"verify_and_get\('([^']+)'\)", f.read())
  if not names:
    sys.exit(f"{cmake_utils}: no verify_and_get(...) calls found, cannot list Dawn's dependencies")
  return [DAWN] + [f"third_party/externals/{name}" for name in names]


def main(argv):
  if len(argv) != 2:
    sys.exit(__doc__)
  skia = os.path.abspath(argv[1])
  deps = parse_deps(os.path.join(skia, "DEPS"))
  wanted = dawn_dependencies(skia)
  missing = [d for d in wanted if d not in deps]
  if missing:
    sys.exit(f"DEPS has no entry for: {', '.join(missing)}")

  # git-sync-deps resolves the directories relative to the DEPS file it reads,
  # so the reduced file has to live in the Skia checkout.
  reduced = os.path.join(skia, "DEPS.dawn")
  with open(reduced, "w") as f:
    f.write("# Generated by sync-dawn-deps.py: the DEPS entries Dawn's CMake build needs.\n")
    f.write("deps = {\n")
    for directory in wanted:
      f.write(f"  {directory!r}: {deps[directory]!r},\n")
    f.write("}\n")

  env = dict(os.environ, GIT_SYNC_DEPS_PATH=reduced, GIT_SYNC_DEPS_SKIP_EMSDK="1")
  try:
    subprocess.check_call(
        [sys.executable, os.path.join(skia, "tools", "git-sync-deps")], env=env)
  finally:
    os.remove(reduced)


if __name__ == "__main__":
  main(sys.argv)
